default_locale = "en-EU"

[[locales]]
locale_id = "en-EU"
html_lang = "en"
url_prefix = "en-eu"
display_name = "English (EU)"
flag = "🇪🇺"

[[locales]]
locale_id = "en-GB"
html_lang = "en-GB"
url_prefix = "en-gb"
display_name = "English (UK)"
flag = "🇬🇧"

[[locales]]
locale_id = "en-US"
html_lang = "en-US"
url_prefix = "en-us"
display_name = "English (US)"
flag = "🇺🇸"

[[locales]]
locale_id = "fr-FR"
html_lang = "fr-FR"
url_prefix = "fr"
display_name = "Français"
flag = "🇫🇷"

[[locales]]
locale_id = "de-DE"
html_lang = "de-DE"
url_prefix = "de"
display_name = "Deutsch"
flag = "🇩🇪"

[[locales]]
locale_id = "sv-SE"
html_lang = "sv-SE"
url_prefix = "sv"
display_name = "Svenska"
flag = "🇸🇪"

[[locales]]
locale_id = "nb-NO"
html_lang = "nb-NO"
url_prefix = "no"
display_name = "Norsk"
flag = "🇳🇴"

[[locales]]
locale_id = "nl-NL"
html_lang = "nl-NL"
url_prefix = "nl"
display_name = "Nederlands"
flag = "🇳🇱"

[[locales]]
locale_id = "fi-FI"
html_lang = "fi-FI"
url_prefix = "fi"
display_name = "Suomi"
flag = "🇫🇮"

[[locales]]
locale_id = "is-IS"
html_lang = "is-IS"
url_prefix = "is"
display_name = "Íslenska"
flag = "🇮🇸"

[[locales]]
locale_id = "es-ES"
html_lang = "es-ES"
url_prefix = "es"
display_name = "Español"
flag = "🇪🇸"

[[locales]]
locale_id = "pt-PT"
html_lang = "pt-PT"
url_prefix = "pt"
display_name = "Português"
flag = "🇵🇹"

[[locales]]
locale_id = "it-IT"
html_lang = "it-IT"
url_prefix = "it"
display_name = "Italiano"
flag = "🇮🇹"

[[locales]]
locale_id = "ja-JP"
html_lang = "ja-JP"
url_prefix = "ja"
display_name = "日本語"
flag = "🇯🇵"

[[locales]]
locale_id = "zh-CN"
html_lang = "zh-CN"
url_prefix = "zh"
display_name = "简体中文"
flag = "🇨🇳"

[[locales]]
locale_id = "zh-TW"
html_lang = "zh-TW"
url_prefix = "zh-tw"
display_name = "繁體中文"
flag = "🇹🇼"

[[locales]]
locale_id = "vi-VN"
html_lang = "vi-VN"
url_prefix = "vi"
display_name = "Tiếng Việt"
flag = "🇻🇳"

[[locales]]
locale_id = "th-TH"
html_lang = "th-TH"
url_prefix = "th"
display_name = "ไทย"
flag = "🇹🇭"

[[locales]]
locale_id = "hi-IN"
html_lang = "hi-IN"
url_prefix = "hi"
display_name = "हिन्दी"
flag = "🇮🇳"

[[locales]]
locale_id = "bn-IN"
html_lang = "bn-IN"
url_prefix = "bn"
display_name = "বাংলা"
flag = "🇮🇳"

[[locales]]
locale_id = "ta-IN"
html_lang = "ta-IN"
url_prefix = "ta"
display_name = "தமிழ்"
flag = "🇮🇳"

[[locales]]
locale_id = "eo-001"
html_lang = "eo"
url_prefix = "eo"
display_name = "Esperanto"
flag = "🌐"

[[locales]]
locale_id = "da-DK"
html_lang = "da-DK"
url_prefix = "da"
display_name = "Dansk"
flag = "🇩🇰"

[[locales]]
locale_id = "la-VA"
html_lang = "la"
url_prefix = "la"
display_name = "Latina"
flag = "🇻🇦"

[[locales]]
locale_id = "gsw-CH"
html_lang = "gsw-CH"
url_prefix = "gsw"
display_name = "Schwiizerdütsch"
flag = "🇨🇭"

[[locales]]
locale_id = "ko-KR"
html_lang = "ko-KR"
url_prefix = "ko"
display_name = "한국어"
flag = "🇰🇷"

[[locales]]
locale_id = "ru-RU"
html_lang = "ru-RU"
url_prefix = "ru"
display_name = "Русский"
flag = "🇷🇺"

[[locales]]
locale_id = "uk-UA"
html_lang = "uk-UA"
url_prefix = "uk"
display_name = "Українська"
flag = "🇺🇦"

[[locales]]
locale_id = "nl-BE"
html_lang = "nl-BE"
url_prefix = "vlaams"
display_name = "Vlaams"
flag = "🇧🇪"

[[locales]]
locale_id = "fr-BE"
html_lang = "fr-BE"
url_prefix = "fr-be"
display_name = "Français (Belgique)"
flag = "🇧🇪"

[[locales]]
locale_id = "fr-CA"
html_lang = "fr-CA"
url_prefix = "fr-ca"
display_name = "Français (Canada)"
flag = "🇨🇦"

[[locales]]
locale_id = "en-CA"
html_lang = "en-CA"
url_prefix = "en-ca"
display_name = "English (Canada)"
flag = "🇨🇦"

[[locales]]
locale_id = "tr-TR"
html_lang = "tr-TR"
url_prefix = "tr"
display_name = "Türkçe"
flag = "🇹🇷"

[[locales]]
locale_id = "lt-LT"
html_lang = "lt-LT"
url_prefix = "lt"
display_name = "Lietuvių"
flag = "🇱🇹"

[[locales]]
locale_id = "lv-LV"
html_lang = "lv-LV"
url_prefix = "lv"
display_name = "Latviešu"
flag = "🇱🇻"

[[locales]]
locale_id = "pl-PL"
html_lang = "pl-PL"
url_prefix = "pl"
display_name = "Polski"
flag = "🇵🇱"

[[locales]]
locale_id = "el-GR"
html_lang = "el-GR"
url_prefix = "el"
display_name = "Ελληνικά"
flag = "🇬🇷"

[[locales]]
locale_id = "hu-HU"
html_lang = "hu-HU"
url_prefix = "hu"
display_name = "Magyar"
flag = "🇭🇺"

[[locales]]
locale_id = "et-EE"
html_lang = "et-EE"
url_prefix = "et"
display_name = "Eesti"
flag = "🇪🇪"

[[locales]]
locale_id = "ovd-SE"
html_lang = "ovd-SE"
url_prefix = "ovd"
display_name = "Övdalsk"
flag = "🇸🇪"

[[locales]]
locale_id = "bg-BG"
html_lang = "bg-BG"
url_prefix = "bg"
display_name = "Български"
flag = "🇧🇬"

[[locales]]
locale_id = "cs-CZ"
html_lang = "cs-CZ"
url_prefix = "cs"
display_name = "Čeština"
flag = "🇨🇿"

[[locales]]
locale_id = "hr-HR"
html_lang = "hr-HR"
url_prefix = "hr"
display_name = "Hrvatski"
flag = "🇭🇷"

[[locales]]
locale_id = "be-BY"
html_lang = "be-BY"
url_prefix = "be"
display_name = "Беларуская"
flag = "🇧🇾"

[[locales]]
locale_id = "ga-IE"
html_lang = "ga-IE"
url_prefix = "ga"
display_name = "Gaeilge"
flag = "🇮🇪"

[[locales]]
locale_id = "lb-LU"
html_lang = "lb-LU"
url_prefix = "lb"
display_name = "Lëtzebuergesch"
flag = "🇱🇺"

[[locales]]
locale_id = "ro-RO"
html_lang = "ro-RO"
url_prefix = "ro"
display_name = "Română"
flag = "🇷🇴"

[[locales]]
locale_id = "sr-RS"
html_lang = "sr-RS"
url_prefix = "sr"
display_name = "Српски"
flag = "🇷🇸"

[[locales]]
locale_id = "nap-IT"
html_lang = "nap-IT"
url_prefix = "nap"
display_name = "Napulitano"
flag = "🇮🇹"

[[locales]]
locale_id = "sk-SK"
html_lang = "sk-SK"
url_prefix = "sk"
display_name = "Slovenčina"
flag = "🇸🇰"

[[locales]]
locale_id = "sl-SI"
html_lang = "sl-SI"
url_prefix = "sl"
display_name = "Slovenščina"
flag = "🇸🇮"

[[locales]]
locale_id = "fy-NL"
html_lang = "fy-NL"
url_prefix = "fy"
display_name = "Frysk"
flag = "🇳🇱"

[[locales]]
locale_id = "se-NO"
html_lang = "se-NO"
url_prefix = "se"
display_name = "Davvisámegiella"
flag = "🇳🇴"

[[locales]]
locale_id = "scn-IT"
html_lang = "scn-IT"
url_prefix = "scn"
display_name = "Sicilianu"
flag = "🇮🇹"

[[locales]]
locale_id = "ar-001"
html_lang = "ar"
dir = "rtl"
url_prefix = "ar"
display_name = "العربية الفصحى"
flag = "🌐"

[[locales]]
locale_id = "ar-AE"
html_lang = "ar-AE"
dir = "rtl"
url_prefix = "ar-ae"
display_name = "العربية الإماراتية"
flag = "🇦🇪"

[[locales]]
locale_id = "ar-EG"
html_lang = "ar-EG"
dir = "rtl"
url_prefix = "ar-eg"
display_name = "العربية المصرية"
flag = "🇪🇬"

[[locales]]
locale_id = "ar-SA"
html_lang = "ar-SA"
dir = "rtl"
url_prefix = "ar-sa"
display_name = "العربية السعودية"
flag = "🇸🇦"

[[locales]]
locale_id = "id-ID"
html_lang = "id-ID"
url_prefix = "id"
display_name = "Bahasa Indonesia"
flag = "🇮🇩"

[[locales]]
locale_id = "ur-PK"
html_lang = "ur-PK"
dir = "rtl"
url_prefix = "ur"
display_name = "اردو"
flag = "🇵🇰"

[[locales]]
locale_id = "mr-IN"
html_lang = "mr-IN"
url_prefix = "mr"
display_name = "मराठी"
flag = "🇮🇳"

[[locales]]
locale_id = "jv-ID"
html_lang = "jv-ID"
url_prefix = "jv"
display_name = "Basa Jawa"
flag = "🇮🇩"

[[locales]]
locale_id = "pt-BR"
html_lang = "pt-BR"
url_prefix = "pt-br"
display_name = "Português (Brasil)"
flag = "🇧🇷"

[[locales]]
locale_id = "es-MX"
html_lang = "es-MX"
url_prefix = "es-mx"
display_name = "Español (México)"
flag = "🇲🇽"

[[locales]]
locale_id = "ms-MY"
html_lang = "ms-MY"
url_prefix = "ms"
display_name = "Bahasa Melayu"
flag = "🇲🇾"

[[locales]]
locale_id = "fil-PH"
html_lang = "fil-PH"
url_prefix = "fil"
display_name = "Filipino"
flag = "🇵🇭"

[[locales]]
locale_id = "fa-IR"
html_lang = "fa-IR"
dir = "rtl"
url_prefix = "fa"
display_name = "فارسی"
flag = "🇮🇷"

[[locales]]
locale_id = "he-IL"
html_lang = "he-IL"
dir = "rtl"
url_prefix = "he"
display_name = "עברית"
flag = "🇮🇱"

[[locales]]
locale_id = "sw-KE"
html_lang = "sw-KE"
url_prefix = "sw"
display_name = "Kiswahili"
flag = "🇰🇪"

[[locales]]
locale_id = "pa-IN"
html_lang = "pa-IN"
url_prefix = "pa"
display_name = "ਪੰਜਾਬੀ"
flag = "🇮🇳"

[[locales]]
locale_id = "te-IN"
html_lang = "te-IN"
url_prefix = "te"
display_name = "తెలుగు"
flag = "🇮🇳"

[[locales]]
locale_id = "gu-IN"
html_lang = "gu-IN"
url_prefix = "gu"
display_name = "ગુજરાતી"
flag = "🇮🇳"

[[locales]]
locale_id = "kn-IN"
html_lang = "kn-IN"
url_prefix = "kn"
display_name = "ಕನ್ನಡ"
flag = "🇮🇳"

[[locales]]
locale_id = "ml-IN"
html_lang = "ml-IN"
url_prefix = "ml"
display_name = "മലയാളം"
flag = "🇮🇳"

[[locales]]
locale_id = "ne-NP"
html_lang = "ne-NP"
url_prefix = "ne"
display_name = "नेपाली"
flag = "🇳🇵"

[[locales]]
locale_id = "si-LK"
html_lang = "si-LK"
url_prefix = "si"
display_name = "සිංහල"
flag = "🇱🇰"

[[locales]]
locale_id = "my-MM"
html_lang = "my-MM"
url_prefix = "my"
display_name = "မြန်မာ"
flag = "🇲🇲"

[[locales]]
locale_id = "km-KH"
html_lang = "km-KH"
url_prefix = "km"
display_name = "ភាសាខ្មែរ"
flag = "🇰🇭"

[[locales]]
locale_id = "lo-LA"
html_lang = "lo-LA"
url_prefix = "lo"
display_name = "ລາວ"
flag = "🇱🇦"

[[locales]]
locale_id = "mn-MN"
html_lang = "mn-MN"
url_prefix = "mn"
display_name = "Монгол"
flag = "🇲🇳"

[[locales]]
locale_id = "ha-NG"
html_lang = "ha-NG"
url_prefix = "ha"
display_name = "Hausa"
flag = "🇳🇬"

[[locales]]
locale_id = "yo-NG"
html_lang = "yo-NG"
url_prefix = "yo"
display_name = "Yorùbá"
flag = "🇳🇬"

[[locales]]
locale_id = "ig-NG"
html_lang = "ig-NG"
url_prefix = "ig"
display_name = "Igbo"
flag = "🇳🇬"

[[locales]]
locale_id = "am-ET"
html_lang = "am-ET"
url_prefix = "am"
display_name = "አማርኛ"
flag = "🇪🇹"

[[locales]]
locale_id = "om-ET"
html_lang = "om-ET"
url_prefix = "om"
display_name = "Afaan Oromoo"
flag = "🇪🇹"

[[locales]]
locale_id = "so-SO"
html_lang = "so-SO"
url_prefix = "so"
display_name = "Soomaali"
flag = "🇸🇴"

[[locales]]
locale_id = "zu-ZA"
html_lang = "zu-ZA"
url_prefix = "zu"
display_name = "isiZulu"
flag = "🇿🇦"

[[locales]]
locale_id = "af-ZA"
html_lang = "af-ZA"
url_prefix = "af"
display_name = "Afrikaans"
flag = "🇿🇦"

[[locales]]
locale_id = "ca-ES"
html_lang = "ca-ES"
url_prefix = "ca"
display_name = "Català"
flag = "🇪🇸"

[[locales]]
locale_id = "eu-ES"
html_lang = "eu-ES"
url_prefix = "eu"
display_name = "Euskara"
flag = "🇪🇸"

[[locales]]
locale_id = "gl-ES"
html_lang = "gl-ES"
url_prefix = "gl"
display_name = "Galego"
flag = "🇪🇸"

[[locales]]
locale_id = "cy-GB"
html_lang = "cy-GB"
url_prefix = "cy"
display_name = "Cymraeg"
flag = "🏴"

[[locales]]
locale_id = "sq-AL"
html_lang = "sq-AL"
url_prefix = "sq"
display_name = "Shqip"
flag = "🇦🇱"

[[locales]]
locale_id = "bs-BA"
html_lang = "bs-BA"
url_prefix = "bs"
display_name = "Bosanski"
flag = "🇧🇦"

[[locales]]
locale_id = "mk-MK"
html_lang = "mk-MK"
url_prefix = "mk"
display_name = "Македонски"
flag = "🇲🇰"

[[locales]]
locale_id = "mt-MT"
html_lang = "mt-MT"
url_prefix = "mt"
display_name = "Malti"
flag = "🇲🇹"

[[locales]]
locale_id = "hy-AM"
html_lang = "hy-AM"
url_prefix = "hy"
display_name = "Հայերեն"
flag = "🇦🇲"

[[locales]]
locale_id = "ka-GE"
html_lang = "ka-GE"
url_prefix = "ka"
display_name = "ქართული"
flag = "🇬🇪"

[[locales]]
locale_id = "az-AZ"
html_lang = "az-AZ"
url_prefix = "az"
display_name = "Azərbaycanca"
flag = "🇦🇿"

[[locales]]
locale_id = "kk-KZ"
html_lang = "kk-KZ"
url_prefix = "kk"
display_name = "Қазақша"
flag = "🇰🇿"

[[locales]]
locale_id = "uz-UZ"
html_lang = "uz-UZ"
url_prefix = "uz"
display_name = "Oʻzbekcha"
flag = "🇺🇿"

[[locales]]
locale_id = "ky-KG"
html_lang = "ky-KG"
url_prefix = "ky"
display_name = "Кыргызча"
flag = "🇰🇬"

[[locales]]
locale_id = "tg-TJ"
html_lang = "tg-TJ"
url_prefix = "tg"
display_name = "Тоҷикӣ"
flag = "🇹🇯"

[[locales]]
locale_id = "tk-TM"
html_lang = "tk-TM"
url_prefix = "tk"
display_name = "Türkmençe"
flag = "🇹🇲"

[[locales]]
locale_id = "ps-AF"
html_lang = "ps-AF"
dir = "rtl"
url_prefix = "ps"
display_name = "پښتو"
flag = "🇦🇫"

[[locales]]
locale_id = "ckb-IQ"
html_lang = "ckb-IQ"
dir = "rtl"
url_prefix = "ckb"
display_name = "کوردیی ناوەندی"
flag = "🇮🇶"

[[locales]]
locale_id = "ku-TR"
html_lang = "ku-TR"
url_prefix = "ku"
display_name = "Kurdî"
flag = "🌐"

[[locales]]
locale_id = "ti-ER"
html_lang = "ti-ER"
url_prefix = "ti"
display_name = "ትግርኛ"
flag = "🇪🇷"

[[locales]]
locale_id = "rw-RW"
html_lang = "rw-RW"
url_prefix = "rw"
display_name = "Kinyarwanda"
flag = "🇷🇼"

[[locales]]
locale_id = "mg-MG"
html_lang = "mg-MG"
url_prefix = "mg"
display_name = "Malagasy"
flag = "🇲🇬"

[[locales]]
locale_id = "sn-ZW"
html_lang = "sn-ZW"
url_prefix = "sn"
display_name = "chiShona"
flag = "🇿🇼"

[[locales]]
locale_id = "xh-ZA"
html_lang = "xh-ZA"
url_prefix = "xh"
display_name = "isiXhosa"
flag = "🇿🇦"
